### ISSUE TITLE
Add reverse to protocol

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-networking#13]
The rover (apparently) needs a reverse functionality.

cc: @Doomfest we talked about this but I don't remember why we chose this organization. Can you elaborate?

**Comment by Doomfest** [comment]
The current motors i think go like this.

0-127 value is reverse
128 is stop
129-255 is forward.


But this will probably change with the new motors so we dont know yet.

The way you did it is roboticsnet-client move 1 ?
why dont we have forward or backward instead of move commnad?

like roboticsnet-client forward <value>
roboticsnet-client reverse <value>

**Comment by Doomfest** [comment]
ROBOTICSNET_COMMAND_MOVE      = 0x01
ROBOTICSNET_COMMAND_TURN      = 0x02
ROBOTICSNET_COMMAND_QUERYPROC = 0x03


we can do 


ROBOTICSNET_COMMAND_FORWARD = 0x00
ROBOTICSNET_COMMAND_REVERSE = 0X01
ROBOTICSNET_COMMAND_TURN_LEFT  = 0x02
ROBOTICSNET_COMMAND_TURN_RIGHT = 0x03


ROBOTICSNET_COMMAND_QUERYPROC = 0x04



your thoughts?

**Comment by psyomn** [comment]
command should be 

~~~~bash
$ roboticsnet-client --move 22
~~~~

and `22` can be any number.

As for renaming move, sure that's fine by me (if you want to handle the renaming parts).
